version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-hello-world_server_1
      APP_PORT: 4000
    volumes:
      - ${APP_DATA_DIR}/data:/data

  server:
    init: true
    image: ghcr.io/mikkmartin/cron-app:main@sha256:291a2cdab21341915fbacb7e5ef8678ba3505d4d583da5d16f0569c359fb4dc6
    restart: on-failure
