version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mikkmartin-cron-jobs_server_1
      APP_PORT: 4000
    volumes:
      - ${APP_DATA_DIR}/data:/data

  server:
    init: true
    image: ghcr.io/mikkmartin/cron-app:main@sha256:06ad657bebae5f73f36ece2430f7e32f3eeae37f8c26efb48e26731f4a84f164
    restart: on-failure
