version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mikkmartin-cron-jobs_server_1
      APP_PORT: 4000
    volumes:
      - ${APP_DATA_DIR}/data:/data

  server:
    init: true
    image: ghcr.io/mikkmartin/cron-app:main@sha256:f2cdfdd6b1e07e190d8ddb16fde7dfdc12a266e4ecbe8b2d8eefbef5e27791a8
    restart: on-failure
